version: 3

tasks:
  clean:
    cmds:
      - rm dashink dashink.exe

  build:
    cmds:
      - go build -v -o dashink cmd/dashink/main.go

  run:
    cmds:
      - go run cmd/dashink/main.go

  run-draw:
    cmds:
      - go run cmd/dashink/main.go -debug -draw

  run-save:
    cmds:
      - go run cmd/dashink/main.go -debug -save
