version: 3

tasks:
  clean:
    cmds:
      - rm main.exe main

  build:
    cmds:
      - go build main.go

  run:
    cmds:
      - go run main.go

  run-draw:
    cmds:
      - go run main.go -draw

  run-save:
    cmds:
      - go run main.go -save
